isi_blnj = input('Masukan 5 barang yang mau kamu beli (pisahkan dengan "," untuk siap barang):')
belanja = list(isi_blnj.split(','))
print('Ini adalah daftar yang kamu buat:')
print(belanja)
hps_blnj = input('Hapus satu batrang yang sudah kamu beli: ')
belanja.remove(hps_blnj)
print()
print("Sekarang sisa belanjaan kamu adalah:")
print(belanja)